### ISSUE TITLE
[Task] API 문서 작성

### ISSUE THREAD

**Issue by sangcode33** [codestates/LegoMore#13]
### ISSUE
- Group:  `sr`
- Type: 
- Detail: 

### TODO
1. [x] API 문서 작성 레퍼런스 참고
2. [x] API 문서 작성 및 수정 
3. [x] 검토 및 최종 완성

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `Sprint__1__`
- Urgency: `High`
