### ISSUE TITLE
[Task] 시스템 아키텍처 구성

### ISSUE THREAD

**Issue by sangcode33** [codestates/LegoMore#16]
### ISSUE
- Group:  `sr`
- Type: 
- Detail: 

### TODO
1. [ ] 서비스 전체 흐름을 설명할 수 있는 시스템 아키텍처 구성
2. [ ] cloudcraft.co 활용 작성 
3. [ ] 검토 및 최종 완성 

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `Sprint__1__`
- Urgency: `High`
