### ISSUE TITLE
[Task] Task 이슈카드 작성 

### ISSUE THREAD

**Issue by sangcode33** [codestates/LegoMore#17]
### ISSUE
- Group: `sr`
- Type: 
- Detail: 

### TODO
1. [ ] Client Task 이슈카드 세부 작성 
2. [ ] Server Task 이슈카드 세부 작성
3. [ ] 팀 검토 및 수정 - 최종 완성

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `Sprint__1__`
- Urgency: `High`
