### ISSUE TITLE
[Task] JWT를 이용한 로그인 / 로그아웃 구현

### ISSUE THREAD

**Issue by sangcode33** [codestates/LegoMore#24]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] MVC 디자인 패턴 사용 컴포넌트 설계
2. [x] 인증 함수 작성
3. [x] 로그인 / 로그아웃 구현

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`
