### ISSUE TITLE
[Task] 랜딩 페이지

### ISSUE THREAD

**Issue by sangcode33** [codestates/LegoMore#27]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 네비게이션 컴포넌트 작성
2. [x] 메인 레이아웃 및 버튼
3. [x] 푸터 컴포넌트 작성

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`, `Middle`, `Low`
